apiVersion: v1
#kind: apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: fastpvc
spec:
  resources:
    requests:
      storage: 5Gi
  volumeMode: Filesystem
  accessModes:
    - ReadWriteOnce
  storageClassName: fast
