apiVersion: v1
kind: Pod
metadata:
  name: dnsutil
  labels:
    app: myapp
spec:
  containers:
   - name: myapp
     image: tutum/dnsutils
     command:
       - sleep infinity
     ports:
      - containerPort: 8080
        protocol: TCP


