apiVersion: v1
kind: Pod
metadata:
  name: myapp-manual
  labels:
    name: myapp-manual
spec:
  containers:
   - name: myapp
     image: luksa/kubia
     ports:
      - containerPort: 8080
        protocol: TCP


