apiVersion: v1
#kind: apiVersion: v1
kind: Pod
metadata:
  name: myappfortune
  labels:
    app: kubia
spec:
  containers:
  - name: html-generator
    image: luksa/fortune
    volumeMounts:
      - name: html
        mountPath: /var/htdocs 
  - name: web-server
    image: nginx:alpine
    volumeMounts:
      - name: html
        mountPath: /usr/share/nginx/html     
        readOnly: true
    ports:
      - containerPort: 8080
        protocol: TCP
  volumes:
     - name: html
       emptyDir: {}    
